#include <iostream>
#include "AppManager.h"

using namespace std;

/*

GRUPO: 47
INTEGRANTES: ALEJO COMEZ, SOFIA BERNIGOLA Y AGUSTIN POSE
VERSIÓN: SOFIA BERNIGOLA

PARA LA ENTREGA DE ESTE PROYECTO UTILIZAMOS DOS VERSIONES DIFERENTES, YA QUE AL MOMENTO DE
FORMAR EL GRUPO, AMBAS PARTES YA CONTABAN CON SU RESPECTIVO TRABAJO FINALIZADO APLICANDO DIFERENTES METODOS.

*/



int main()
{
    AppManager app;
    app.menuPrincipal();
}
